baseURL = 'https://gohugo.io/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "bookmarks"
    weight = 2
    url = "bookmarks"

[params]
user = "hellows;"
hostname = "gohugo"
  [params.author]
    name = "A. MertoÄŸlu"  # Website and RSS feed author
    email = "abdullah.mertoglu99@gmail.com"  # RSS feed email address


readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "ğŸ± github"
url = "https://github.com/uiframer"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "ğŸ¦ twitter"
url = "https://x.com/amertoglu16"
aria = "Twitter Profile"

[[params.social]]
key = 2
name = "âœï¸ send"
url = "mailto:abdullah.mertoglu99@gmail.com"
aria = "My e-Mail Address"
